name: Проверка Node.js проекта

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачиваем код из репозитория
        uses: actions/checkout@v4

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Проверяем версию Node
        run: node --version